name: Start tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies and tools
        run: |
          python3 -m venv venv
          ./venv/bin/pip install -r requirements.txt
          ./venv/bin/pip install pytest-cov coveralls

      - name: Run tests with pytest and generate coverage report
        run: |
          ./venv/bin/pytest --cov=src --cov-report=xml --cov-report=term ./src/tests/

      - name: Upload coverage report to Coveralls
        run: ./venv/bin/coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_SCANNER_OPTS: "-Dsonar.python.coverage.reportPaths=coverage.xml"